/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import utils.Session;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.User;



/**
 *
 * @author darwisy
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private final Color primaryColor = new Color (81,108,248);
    private final Color activeColor = new Color (101,135,245);
    private final Color hoverTextColor = new Color (204,204,204);
    private final Color whiteColor = new Color (255,255,255);
    
    public Dashboard(String role) {
        
        initComponents();
        // Validasi session
        if (!Session.isLoggedIn()) {
            JOptionPane.showMessageDialog(this, 
                "Anda harus login terlebih dahulu", 
                "Akses Ditolak", 
                JOptionPane.WARNING_MESSAGE);
            new FormLogin().setVisible(true);
            this.dispose();
            return;
        }

        // Set judul window dengan nama user
        this.setTitle("TalentSphere - " + Session.getCurrentUser().getUsername());
        pBodyContent.add(new PanelDashboard());
         setVisible(true);
         tampilkanNamaUser();
         
         
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pMenuDashboard = new javax.swing.JPanel();
        dashboardAdmin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pMenuUser = new javax.swing.JPanel();
        menuUser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pMenuKaryawan = new javax.swing.JPanel();
        menuKaryawan = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pMenuJabatan = new javax.swing.JPanel();
        menuJabatan = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pMenuDepartemen = new javax.swing.JPanel();
        menuDepartemen = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pMenuAbsensi = new javax.swing.JPanel();
        menuAbsensi = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pMenuPenggajian = new javax.swing.JPanel();
        menuPenggajian = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pMenuCuti = new javax.swing.JPanel();
        menuCuti = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pMenuRekrutmen = new javax.swing.JPanel();
        menuRekrutmen = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pMenuLaporanAbsensi = new javax.swing.JPanel();
        menuLaporanAbsensi = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pMenuLaporanPenggajian = new javax.swing.JPanel();
        menuLaporanPenggajian = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        pMenuLaporanCuti = new javax.swing.JPanel();
        menuLaporanCuti = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        pMenuLaporanKontrak = new javax.swing.JPanel();
        menuLogout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pIsi = new javax.swing.JPanel();
        pHeader = new javax.swing.JPanel();
        labelRole = new javax.swing.JLabel();
        pBody = new javax.swing.JPanel();
        pBodyContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pMenu.setBackground(new java.awt.Color(81, 108, 248));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Talent Sphere");

        pMenuDashboard.setBackground(new java.awt.Color(81, 108, 248));

        dashboardAdmin.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        dashboardAdmin.setForeground(new java.awt.Color(255, 255, 255));
        dashboardAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardAdmin.setText("Dashboard");
        dashboardAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardAdminMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dashboard-menu-24px.png"))); // NOI18N

        javax.swing.GroupLayout pMenuDashboardLayout = new javax.swing.GroupLayout(pMenuDashboard);
        pMenuDashboard.setLayout(pMenuDashboardLayout);
        pMenuDashboardLayout.setHorizontalGroup(
            pMenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuDashboardLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(dashboardAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pMenuDashboardLayout.setVerticalGroup(
            pMenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dashboardAdmin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenuUser.setBackground(new java.awt.Color(81, 108, 248));

        menuUser.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        menuUser.setForeground(new java.awt.Color(255, 255, 255));
        menuUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuUser.setText("User");
        menuUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuUserMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/karyawan-menu-24px.png"))); // NOI18N

        javax.swing.GroupLayout pMenuUserLayout = new javax.swing.GroupLayout(pMenuUser);
        pMenuUser.setLayout(pMenuUserLayout);
        pMenuUserLayout.setHorizontalGroup(
            pMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuUserLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(menuUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pMenuUserLayout.setVerticalGroup(
            pMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(menuUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenuKaryawan.setBackground(new java.awt.Color(81, 108, 248));

        menuKaryawan.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        menuKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        menuKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuKaryawan.setText("Karyawan");
        menuKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuKaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuKaryawanMouseExited(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/karyawan-menu-24px.png"))); // NOI18N

        javax.swing.GroupLayout pMenuKaryawanLayout = new javax.swing.GroupLayout(pMenuKaryawan);
        pMenuKaryawan.setLayout(pMenuKaryawanLayout);
        pMenuKaryawanLayout.setHorizontalGroup(
            pMenuKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuKaryawanLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(menuKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pMenuKaryawanLayout.setVerticalGroup(
            pMenuKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuKaryawanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(menuKaryawan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenuJabatan.setBackground(new java.awt.Color(81, 108, 248));

        menuJabatan.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        menuJabatan.setForeground(new java.awt.Color(255, 255, 255));
        menuJabatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuJabatan.setText("Jabatan");
        menuJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuJabatanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuJabatanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuJabatanMouseExited(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jabatan-menu-24px.png"))); // NOI18N

        javax.swing.GroupLayout pMenuJabatanLayout = new javax.swing.GroupLayout(pMenuJabatan);
        pMenuJabatan.setLayout(pMenuJabatanLayout);
        pMenuJabatanLayout.setHorizontalGroup(
            pMenuJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuJabatanLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(menuJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pMenuJabatanLayout.setVerticalGroup(
            pMenuJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuJabatanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(menuJabatan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenuDepartemen.setBackground(new java.awt.Color(81, 108, 248));

        menuDepartemen.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        menuDepartemen.setForeground(new java.awt.Color(255, 255, 255));
        menuDepartemen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuDepartemen.setText("Departemen");
        menuDepartemen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDepartemenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuDepartemenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuDepartemenMouseExited(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Departemen-menu-24px.png"))); // NOI18N

        javax.swing.GroupLayout pMenuDepartemenLayout = new javax.swing.GroupLayout(pMenuDepartemen);
        pMenuDepartemen.setLayout(pMenuDepartemenLayout);
        pMenuDepartemenLayout.setHorizontalGroup(
            pMenuDepartemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuDepartemenLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(menuDepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pMenuDepartemenLayout.setVerticalGroup(
            pMenuDepartemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuDepartemenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuDepartemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(menuDepartemen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenuAbsensi.setBackground(new java.awt.Color(81, 108, 248));

        menuAbsensi.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        menuAbsensi.setForeground(new java.awt.Color(255, 255, 255));
        menuAbsensi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuAbsensi.setText("Absensi");
        menuAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAbsensiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuAbsensiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuAbsensiMouseExited(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Absensi-menu-24px.png"))); // NOI18N

        javax.swing.GroupLayout pMenuAbsensiLayout = new javax.swing.GroupLayout(pMenuAbsensi);
        pMenuAbsensi.setLayout(pMenuAbsensiLayout);
        pMenuAbsensiLayout.setHorizontalGroup(
            pMenuAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuAbsensiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(menuAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        pMenuAbsensiLayout.setVerticalGroup(
            pMenuAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuAbsensiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(menuAbsensi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenuPenggajian.setBackground(new java.awt.Color(81, 108, 248));

        menuPenggajian.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        menuPenggajian.setForeground(new java.awt.Color(255, 255, 255));
        menuPenggajian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuPenggajian.setText("Penggajian");
        menuPenggajian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPenggajianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPenggajianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPenggajianMouseExited(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Penggajian-menu-24px.png"))); // NOI18N

        javax.swing.GroupLayout pMenuPenggajianLayout = new javax.swing.GroupLayout(pMenuPenggajian);
        pMenuPenggajian.setLayout(pMenuPenggajianLayout);
        pMenuPenggajianLayout.setHorizontalGroup(
            pMenuPenggajianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuPenggajianLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(menuPenggajian, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pMenuPenggajianLayout.setVerticalGroup(
            pMenuPenggajianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuPenggajianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuPenggajianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(menuPenggajian))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenuCuti.setBackground(new java.awt.Color(81, 108, 248));

        menuCuti.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        menuCuti.setForeground(new java.awt.Color(255, 255, 255));
        menuCuti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuCuti.setText("Cuti");
        menuCuti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCutiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuCutiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuCutiMouseExited(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cuti-menu-24px.png"))); // NOI18N

        javax.swing.GroupLayout pMenuCutiLayout = new javax.swing.GroupLayout(pMenuCuti);
        pMenuCuti.setLayout(pMenuCutiLayout);
        pMenuCutiLayout.setHorizontalGroup(
            pMenuCutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuCutiLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(menuCuti, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pMenuCutiLayout.setVerticalGroup(
            pMenuCutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuCutiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuCutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(menuCuti))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenuRekrutmen.setBackground(new java.awt.Color(81, 108, 248));

        menuRekrutmen.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        menuRekrutmen.setForeground(new java.awt.Color(255, 255, 255));
        menuRekrutmen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuRekrutmen.setText("Rekrutmen");
        menuRekrutmen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRekrutmenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuRekrutmenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuRekrutmenMouseExited(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rekrutmen-menu-24px.png"))); // NOI18N

        javax.swing.GroupLayout pMenuRekrutmenLayout = new javax.swing.GroupLayout(pMenuRekrutmen);
        pMenuRekrutmen.setLayout(pMenuRekrutmenLayout);
        pMenuRekrutmenLayout.setHorizontalGroup(
            pMenuRekrutmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuRekrutmenLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(menuRekrutmen, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pMenuRekrutmenLayout.setVerticalGroup(
            pMenuRekrutmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuRekrutmenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuRekrutmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(menuRekrutmen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenuLaporanAbsensi.setBackground(new java.awt.Color(81, 108, 248));

        menuLaporanAbsensi.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        menuLaporanAbsensi.setForeground(new java.awt.Color(255, 255, 255));
        menuLaporanAbsensi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuLaporanAbsensi.setText("Absensi");
        menuLaporanAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLaporanAbsensiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLaporanAbsensiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLaporanAbsensiMouseExited(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Laporan-menu-24px.png"))); // NOI18N

        javax.swing.GroupLayout pMenuLaporanAbsensiLayout = new javax.swing.GroupLayout(pMenuLaporanAbsensi);
        pMenuLaporanAbsensi.setLayout(pMenuLaporanAbsensiLayout);
        pMenuLaporanAbsensiLayout.setHorizontalGroup(
            pMenuLaporanAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuLaporanAbsensiLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(menuLaporanAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pMenuLaporanAbsensiLayout.setVerticalGroup(
            pMenuLaporanAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLaporanAbsensiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuLaporanAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(menuLaporanAbsensi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenuLaporanPenggajian.setBackground(new java.awt.Color(81, 108, 248));

        menuLaporanPenggajian.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        menuLaporanPenggajian.setForeground(new java.awt.Color(255, 255, 255));
        menuLaporanPenggajian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuLaporanPenggajian.setText("Penggajian");
        menuLaporanPenggajian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLaporanPenggajianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLaporanPenggajianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLaporanPenggajianMouseExited(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Laporan-menu-24px.png"))); // NOI18N

        javax.swing.GroupLayout pMenuLaporanPenggajianLayout = new javax.swing.GroupLayout(pMenuLaporanPenggajian);
        pMenuLaporanPenggajian.setLayout(pMenuLaporanPenggajianLayout);
        pMenuLaporanPenggajianLayout.setHorizontalGroup(
            pMenuLaporanPenggajianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuLaporanPenggajianLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(menuLaporanPenggajian, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pMenuLaporanPenggajianLayout.setVerticalGroup(
            pMenuLaporanPenggajianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLaporanPenggajianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuLaporanPenggajianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(menuLaporanPenggajian))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenuLaporanCuti.setBackground(new java.awt.Color(81, 108, 248));

        menuLaporanCuti.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        menuLaporanCuti.setForeground(new java.awt.Color(255, 255, 255));
        menuLaporanCuti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuLaporanCuti.setText("Cuti");
        menuLaporanCuti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLaporanCutiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLaporanCutiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLaporanCutiMouseExited(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Laporan-menu-24px.png"))); // NOI18N

        javax.swing.GroupLayout pMenuLaporanCutiLayout = new javax.swing.GroupLayout(pMenuLaporanCuti);
        pMenuLaporanCuti.setLayout(pMenuLaporanCutiLayout);
        pMenuLaporanCutiLayout.setHorizontalGroup(
            pMenuLaporanCutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuLaporanCutiLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(menuLaporanCuti, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pMenuLaporanCutiLayout.setVerticalGroup(
            pMenuLaporanCutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLaporanCutiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuLaporanCutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(menuLaporanCuti))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pMenuLaporanKontrak.setBackground(new java.awt.Color(81, 108, 248));

        menuLogout.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        menuLogout.setForeground(new java.awt.Color(255, 255, 255));
        menuLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuLogout.setText("Logout");
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pMenuLaporanKontrakLayout = new javax.swing.GroupLayout(pMenuLaporanKontrak);
        pMenuLaporanKontrak.setLayout(pMenuLaporanKontrakLayout);
        pMenuLaporanKontrakLayout.setHorizontalGroup(
            pMenuLaporanKontrakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuLaporanKontrakLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        pMenuLaporanKontrakLayout.setVerticalGroup(
            pMenuLaporanKontrakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuLaporanKontrakLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(menuLogout))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MASTER DATA");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LAPORAN");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TRANSAKSI");

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pMenuLayout = new javax.swing.GroupLayout(pMenu);
        pMenu.setLayout(pMenuLayout);
        pMenuLayout.setHorizontalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuLaporanAbsensi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuLaporanPenggajian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuLaporanCuti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuLaporanKontrak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuKaryawan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuJabatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuDepartemen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuAbsensi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuPenggajian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuCuti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pMenuRekrutmen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMenuLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pMenuLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pMenuLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMenuLayout.setVerticalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pMenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMenuUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMenuKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMenuJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMenuDepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pMenuAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMenuPenggajian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMenuCuti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMenuRekrutmen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMenuLaporanAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMenuLaporanPenggajian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMenuLaporanCuti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMenuLaporanKontrak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(pMenu, java.awt.BorderLayout.LINE_START);

        pIsi.setLayout(new java.awt.BorderLayout());

        pHeader.setBackground(new java.awt.Color(255, 255, 255));

        labelRole.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        labelRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRole.setText("Role");

        javax.swing.GroupLayout pHeaderLayout = new javax.swing.GroupLayout(pHeader);
        pHeader.setLayout(pHeaderLayout);
        pHeaderLayout.setHorizontalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHeaderLayout.createSequentialGroup()
                .addContainerGap(777, Short.MAX_VALUE)
                .addComponent(labelRole, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pHeaderLayout.setVerticalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelRole)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pIsi.add(pHeader, java.awt.BorderLayout.PAGE_START);

        pBody.setBackground(new java.awt.Color(226, 230, 253));

        pBodyContent.setBackground(new java.awt.Color(226, 230, 253));
        pBodyContent.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pBodyLayout = new javax.swing.GroupLayout(pBody);
        pBody.setLayout(pBodyLayout);
        pBodyLayout.setHorizontalGroup(
            pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBodyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pBodyContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pBodyLayout.setVerticalGroup(
            pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBodyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pBodyContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pIsi.add(pBody, java.awt.BorderLayout.CENTER);

        getContentPane().add(pIsi, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void resetMenuColors(){
        pMenuDashboard.setBackground(primaryColor);
        pMenuUser.setBackground(primaryColor);
        pMenuKaryawan.setBackground(primaryColor);
        pMenuJabatan.setBackground(primaryColor);
        pMenuDepartemen.setBackground(primaryColor);
        pMenuAbsensi.setBackground(primaryColor);
        pMenuPenggajian.setBackground(primaryColor);
        pMenuCuti.setBackground(primaryColor);
        pMenuRekrutmen.setBackground(primaryColor);
        
        pMenuLaporanAbsensi.setBackground(primaryColor);
        pMenuLaporanPenggajian.setBackground(primaryColor);
        pMenuLaporanCuti.setBackground(primaryColor);
        pMenuLaporanKontrak.setBackground(primaryColor);
        
                
    }
    private void dashboardAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardAdminMouseClicked
        resetMenuColors();
        pMenuDashboard.setBackground(activeColor); 
        pBodyContent.removeAll();
        pBodyContent.add(new PanelDashboard());
        pBodyContent.repaint();
        pBodyContent.revalidate();
    }//GEN-LAST:event_dashboardAdminMouseClicked

    private void dashboardAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardAdminMouseEntered
        dashboardAdmin.setForeground(hoverTextColor);
    }//GEN-LAST:event_dashboardAdminMouseEntered

    private void dashboardAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardAdminMouseExited
        dashboardAdmin.setForeground(whiteColor);
    }//GEN-LAST:event_dashboardAdminMouseExited

    private void menuUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUserMouseClicked
        resetMenuColors();
        pMenuUser.setBackground(activeColor); 
        pBodyContent.removeAll();
        pBodyContent.add(new DataUser());
        pBodyContent.repaint();
        pBodyContent.revalidate();
    }//GEN-LAST:event_menuUserMouseClicked

    private void menuUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUserMouseEntered
        menuUser.setForeground(hoverTextColor);
    }//GEN-LAST:event_menuUserMouseEntered

    private void menuUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUserMouseExited
        menuUser.setForeground(whiteColor);

    }//GEN-LAST:event_menuUserMouseExited

    private void menuKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKaryawanMouseClicked
        resetMenuColors();
        pMenuKaryawan.setBackground(activeColor); 
        pBodyContent.removeAll();
        pBodyContent.add(new DataKaryawan());
        pBodyContent.repaint();
        pBodyContent.revalidate();
    }//GEN-LAST:event_menuKaryawanMouseClicked

    private void menuKaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKaryawanMouseEntered
        menuKaryawan.setForeground(hoverTextColor);
    }//GEN-LAST:event_menuKaryawanMouseEntered

    private void menuKaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKaryawanMouseExited
        menuKaryawan.setForeground(whiteColor);
    }//GEN-LAST:event_menuKaryawanMouseExited

    private void menuJabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuJabatanMouseClicked
        resetMenuColors();
        pMenuJabatan.setBackground(activeColor); 
        pBodyContent.removeAll();
        pBodyContent.add(new DataJabatan());
        pBodyContent.repaint();
        pBodyContent.revalidate();
    }//GEN-LAST:event_menuJabatanMouseClicked

    private void menuJabatanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuJabatanMouseEntered
        menuJabatan.setForeground(hoverTextColor);
    }//GEN-LAST:event_menuJabatanMouseEntered

    private void menuJabatanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuJabatanMouseExited
        menuJabatan.setForeground(whiteColor);
    }//GEN-LAST:event_menuJabatanMouseExited

    private void menuDepartemenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDepartemenMouseClicked
        resetMenuColors();
        pMenuDepartemen.setBackground(activeColor); 
        pBodyContent.removeAll();
        pBodyContent.add(new DataDepartemen());
        pBodyContent.repaint();
        pBodyContent.revalidate();
    }//GEN-LAST:event_menuDepartemenMouseClicked

    private void menuDepartemenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDepartemenMouseEntered
        menuDepartemen.setForeground(hoverTextColor);
    }//GEN-LAST:event_menuDepartemenMouseEntered

    private void menuDepartemenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDepartemenMouseExited
        menuDepartemen.setForeground(whiteColor);
    }//GEN-LAST:event_menuDepartemenMouseExited

    private void menuAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbsensiMouseClicked
        resetMenuColors();
        pMenuAbsensi.setBackground(activeColor); 
        pBodyContent.removeAll();
        pBodyContent.add(new TrxAbsensi());
        pBodyContent.repaint();
        pBodyContent.revalidate();
    }//GEN-LAST:event_menuAbsensiMouseClicked

    private void menuAbsensiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbsensiMouseEntered
        menuAbsensi.setForeground(hoverTextColor);
    }//GEN-LAST:event_menuAbsensiMouseEntered

    private void menuAbsensiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbsensiMouseExited
        menuAbsensi.setForeground(whiteColor);
    }//GEN-LAST:event_menuAbsensiMouseExited

    private void menuPenggajianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPenggajianMouseClicked
        resetMenuColors();
        pMenuPenggajian.setBackground(activeColor); 
        pBodyContent.removeAll();
        pBodyContent.add(new TrxPenggajian());
        pBodyContent.repaint();
        pBodyContent.revalidate();
    }//GEN-LAST:event_menuPenggajianMouseClicked

    private void menuPenggajianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPenggajianMouseEntered
        menuPenggajian.setForeground(hoverTextColor);
    }//GEN-LAST:event_menuPenggajianMouseEntered

    private void menuPenggajianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPenggajianMouseExited
        menuPenggajian.setForeground(whiteColor);
    }//GEN-LAST:event_menuPenggajianMouseExited

    private void menuCutiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCutiMouseClicked
        resetMenuColors();
        pMenuCuti.setBackground(activeColor); 
        pBodyContent.removeAll();
        pBodyContent.add(new TrxCuti());
        pBodyContent.repaint();
        pBodyContent.revalidate();
    }//GEN-LAST:event_menuCutiMouseClicked

    private void menuCutiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCutiMouseEntered
        menuCuti.setForeground(hoverTextColor);
    }//GEN-LAST:event_menuCutiMouseEntered

    private void menuCutiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCutiMouseExited
        menuCuti.setForeground(whiteColor);
    }//GEN-LAST:event_menuCutiMouseExited

    private void menuRekrutmenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRekrutmenMouseClicked
        resetMenuColors();
        pMenuRekrutmen.setBackground(activeColor); 
        pBodyContent.removeAll();
        pBodyContent.add(new TrxRekrutmen());
        pBodyContent.repaint();
        pBodyContent.revalidate();
    }//GEN-LAST:event_menuRekrutmenMouseClicked

    private void menuRekrutmenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRekrutmenMouseEntered
        menuRekrutmen.setForeground(hoverTextColor);
    }//GEN-LAST:event_menuRekrutmenMouseEntered

    private void menuRekrutmenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRekrutmenMouseExited
        menuRekrutmen.setForeground(whiteColor);
    }//GEN-LAST:event_menuRekrutmenMouseExited

    private void menuLaporanAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanAbsensiMouseClicked
        resetMenuColors();
        pMenuLaporanAbsensi.setBackground(activeColor); 
        pBodyContent.removeAll();
        pBodyContent.add(new ReportAbsensi());
        pBodyContent.repaint();
        pBodyContent.revalidate();
    }//GEN-LAST:event_menuLaporanAbsensiMouseClicked

    private void menuLaporanAbsensiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanAbsensiMouseEntered
        menuLaporanAbsensi.setForeground(hoverTextColor);
    }//GEN-LAST:event_menuLaporanAbsensiMouseEntered

    private void menuLaporanAbsensiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanAbsensiMouseExited
        menuLaporanAbsensi.setForeground(whiteColor);
    }//GEN-LAST:event_menuLaporanAbsensiMouseExited

    private void menuLaporanPenggajianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanPenggajianMouseClicked
        resetMenuColors();
        pMenuLaporanPenggajian.setBackground(activeColor); 
        pBodyContent.removeAll();
        pBodyContent.add(new ReportPenggajian());
        pBodyContent.repaint();
        pBodyContent.revalidate();
    }//GEN-LAST:event_menuLaporanPenggajianMouseClicked

    private void menuLaporanPenggajianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanPenggajianMouseEntered
        menuLaporanPenggajian.setForeground(hoverTextColor);
    }//GEN-LAST:event_menuLaporanPenggajianMouseEntered

    private void menuLaporanPenggajianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanPenggajianMouseExited
        menuLaporanPenggajian.setForeground(whiteColor);
    }//GEN-LAST:event_menuLaporanPenggajianMouseExited

    private void menuLaporanCutiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanCutiMouseClicked
        resetMenuColors();
        pMenuLaporanCuti.setBackground(activeColor); 
        pBodyContent.removeAll();
        pBodyContent.add(new ReportCuti());
        pBodyContent.repaint();
        pBodyContent.revalidate();
    }//GEN-LAST:event_menuLaporanCutiMouseClicked

    private void menuLaporanCutiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanCutiMouseEntered
        menuLaporanCuti.setForeground(hoverTextColor);
    }//GEN-LAST:event_menuLaporanCutiMouseEntered

    private void menuLaporanCutiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanCutiMouseExited
        menuLaporanCuti.setForeground(whiteColor);
    }//GEN-LAST:event_menuLaporanCutiMouseExited

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        
    int confirm = JOptionPane.showConfirmDialog(
        this, 
        "Apakah Anda yakin ingin keluar dari sistem?", 
        "Konfirmasi Logout", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
    
    if (confirm == JOptionPane.YES_OPTION) {
        
        System.out.println("User " + Session.getCurrentUser().getUsername() + " melakukan logout");
        
        
        Session.clear();
        
        
        FormLogin loginForm = new FormLogin();
        loginForm.setVisible(true);
        
        
        this.dispose();
    }
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLogoutMouseEntered

    private void menuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLogoutMouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel menuAbsensi;
    private javax.swing.JLabel menuCuti;
    private javax.swing.JLabel menuDepartemen;
    private javax.swing.JLabel menuJabatan;
    private javax.swing.JLabel menuKaryawan;
    private javax.swing.JLabel menuLaporanAbsensi;
    private javax.swing.JLabel menuLaporanCuti;
    private javax.swing.JLabel menuLaporanPenggajian;
    private javax.swing.JLabel menuLogout;
    private javax.swing.JLabel menuPenggajian;
    private javax.swing.JLabel menuRekrutmen;
    private javax.swing.JLabel menuUser;
    private javax.swing.JPanel pBody;
    private javax.swing.JPanel pBodyContent;
    private javax.swing.JPanel pHeader;
    private javax.swing.JPanel pIsi;
    private javax.swing.JPanel pMenu;
    private javax.swing.JPanel pMenuAbsensi;
    private javax.swing.JPanel pMenuCuti;
    private javax.swing.JPanel pMenuDashboard;
    private javax.swing.JPanel pMenuDepartemen;
    private javax.swing.JPanel pMenuJabatan;
    private javax.swing.JPanel pMenuKaryawan;
    private javax.swing.JPanel pMenuLaporanAbsensi;
    private javax.swing.JPanel pMenuLaporanCuti;
    private javax.swing.JPanel pMenuLaporanKontrak;
    private javax.swing.JPanel pMenuLaporanPenggajian;
    private javax.swing.JPanel pMenuPenggajian;
    private javax.swing.JPanel pMenuRekrutmen;
    private javax.swing.JPanel pMenuUser;
    // End of variables declaration//GEN-END:variables

    private void tampilkanNamaUser() {
        User user = Session.getCurrentUser();
        
        labelRole.setText(user.getRole());

    }
    
        

}
