/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;


import controllers.DepartemenController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Departemen;

/**
 *
 * @author darwisy
 */
public class DataDepartemen extends javax.swing.JPanel {

    /**
     * Creates new form User
     */
    public DataDepartemen() {
        initComponents();
        setTableUsers();
        loadUsers();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDepartemen = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        panelAdd = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnTambahBatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tambahNama = new javax.swing.JTextField();
        tambahID = new javax.swing.JTextField();
        btnTambahReset = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setText("Master Data > Departemen");

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setText("Data Departemen");

        tabelDepartemen.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tabelDepartemen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDepartemen.setGridColor(new java.awt.Color(204, 204, 204));
        tabelDepartemen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDepartemenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDepartemen);

        txtSearch.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtSearch.setText("Search...");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(81, 108, 248));
        btnTambah.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.setBorder(null);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(248, 173, 80));
        btnBatal.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.setBorder(null);
        btnBatal.setPreferredSize(new java.awt.Dimension(62, 22));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(248, 80, 108));
        btnDelete.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Hapus");
        btnDelete.setBorder(null);
        btnDelete.setPreferredSize(new java.awt.Dimension(62, 22));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewLayout.createSequentialGroup()
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelViewLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panelMain.add(panelView, "card9");

        panelAdd.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Master Data > Departemen");

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel4.setText("Tambah Data Departemen");

        btnSimpan.setBackground(new java.awt.Color(81, 108, 248));
        btnSimpan.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTambahBatal.setBackground(new java.awt.Color(248, 173, 80));
        btnTambahBatal.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnTambahBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahBatal.setText("Batal");
        btnTambahBatal.setBorder(null);
        btnTambahBatal.setMaximumSize(new java.awt.Dimension(90, 28));
        btnTambahBatal.setMinimumSize(new java.awt.Dimension(90, 28));
        btnTambahBatal.setPreferredSize(new java.awt.Dimension(90, 28));
        btnTambahBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBatalActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Nama Departemen");

        tambahNama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        tambahID.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tambahNama)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahID, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288)
                .addComponent(tambahID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        btnTambahReset.setBackground(new java.awt.Color(51, 51, 51));
        btnTambahReset.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnTambahReset.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahReset.setText("Reset");
        btnTambahReset.setBorder(null);
        btnTambahReset.setMaximumSize(new java.awt.Dimension(90, 28));
        btnTambahReset.setMinimumSize(new java.awt.Dimension(90, 28));
        btnTambahReset.setPreferredSize(new java.awt.Dimension(90, 28));
        btnTambahReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 397, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddLayout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnTambahReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnTambahBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelMain.add(panelAdd, "card9");

        add(panelMain, "card9");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String currentText = btnSimpan.getText();

        switch (currentText) {
            case "Tambah":
                btnSimpan.setText("Simpan");
                break;
            case "Simpan":
                insertData();
                break;

            case "Perbarui":
                updateData();
                break;
        }
        
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        panelMain.removeAll();
        panelMain.add(panelAdd);
        panelMain.repaint();
        panelMain.revalidate();
        tambahID.setVisible(false);
        
        if (btnTambah.getText().equals("Ubah")) {
            dataTable(); 
            btnSimpan.setText("Perbarui");
        } else {
            resetForm(); 
            btnSimpan.setText("Simpan");
        }

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTambahBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBatalActionPerformed
        showPanelView();
        loadUsers();
        resetForm();
        if(btnTambah.getText().equals("Ubah")){
            btnTambah.setText("Tambah");
        }
    }//GEN-LAST:event_btnTambahBatalActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        searchData();
    }//GEN-LAST:event_txtSearchKeyTyped

    private void btnTambahResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahResetActionPerformed
        resetForm();
    }//GEN-LAST:event_btnTambahResetActionPerformed

    private void tabelDepartemenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDepartemenMouseClicked
        if(btnTambah.getText().equals("Tambah")){
            btnTambah.setText("Ubah");
        }
        btnBatal.setVisible(true);
        btnDelete.setVisible(true);
    }//GEN-LAST:event_tabelDepartemenMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        showPanelView();
        loadUsers();
        resetForm();
         if(btnTambah.getText().equals("Ubah")){
            btnTambah.setText("Tambah");
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteData();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahBatal;
    private javax.swing.JButton btnTambahReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelView;
    private javax.swing.JTable tabelDepartemen;
    private javax.swing.JTextField tambahID;
    private javax.swing.JTextField tambahNama;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    
    private void showPanelView(){
        panelMain.removeAll();
        panelMain.add(panelView);
        btnBatal.setVisible(false);
        btnDelete.setVisible(false);
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    private void loadUsers() {
        btnBatal.setVisible(false);
        btnDelete.setVisible(false);
        DepartemenController departemenController = new DepartemenController();
        List<Departemen> departemens = departemenController.getAllDepartemen();

        DefaultTableModel model = (DefaultTableModel)tabelDepartemen.getModel(); 
        model.setRowCount(0);

        int no = 1;
        if (departemens != null) {
            for (Departemen departemen : departemens) {
                model.addRow(new Object[]{
                    no++,                   
                    departemen.getId(),     
                    departemen.getNamaDepartemen()
                });
            }
        }
    }

    private void setTableUsers() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        // Add columns
        model.addColumn("No");
        model.addColumn("ID");
        model.addColumn("Nama Departemen");

        tabelDepartemen.setModel(model);

        // Set column widths
        tabelDepartemen.getColumnModel().getColumn(0).setPreferredWidth(5);  
        tabelDepartemen.getColumnModel().getColumn(1).setMinWidth(0);         
        tabelDepartemen.getColumnModel().getColumn(1).setMaxWidth(0);
        tabelDepartemen.getColumnModel().getColumn(1).setWidth(0);
        tabelDepartemen.getColumnModel().getColumn(2).setPreferredWidth(300); 

        // Optional: Set row height
        tabelDepartemen.setRowHeight(25);
    }

    private void resetForm() {
        tambahNama.setText("");
    }
    
    private void searchData() {
        String keyword = txtSearch.getText();
        DepartemenController departemenController = new DepartemenController();
        List<Departemen> departemens = departemenController.searchDepartemens(keyword);

        DefaultTableModel model = (DefaultTableModel) tabelDepartemen.getModel();
        model.setRowCount(0);

        int no = 1;
        for (Departemen departemen : departemens) {
            model.addRow(new Object[]{
                no++,                   
                departemen.getId(),     
                departemen.getNamaDepartemen()
            });
        }
    }

   private void dataTable(){
        panelView.setVisible(false);
        panelAdd.setVisible(true);

        int row = tabelDepartemen.getSelectedRow();
        jLabel4.setText("Ubah Data Departemen");


        tambahNama.setText(tabelDepartemen.getValueAt(row, 2).toString());


        String id = tabelDepartemen.getValueAt(row, 1).toString(); 
        tambahID.setText(id);
        tambahID.setVisible(false);
    }
    private void insertData() {
        tambahID.setVisible(false);
        String nama = tambahNama.getText();

        
        Departemen departemen = new Departemen();
        departemen.setNamaDepartemen(nama);
        
        
        DepartemenController departemenController = new DepartemenController();
        boolean success = departemenController.insertDepartemen(departemen);

        if (success) {
            JOptionPane.showMessageDialog(this, "Departemen berhasil ditambahkan!");
            loadUsers(); 
            resetForm(); 
            showPanelView(); 
            btnTambah.setText("Tambah");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan Departemen.");
        }
    }

    private void updateData() {
        int id = Integer.parseInt(tambahID.getText()); 
        String nama = tambahNama.getText();
        

        DepartemenController departemenController = new DepartemenController();
        Departemen departemen = new Departemen();
        
        departemen.setId(id);
        departemen.setNamaDepartemen(nama);
        boolean success = departemenController.updateDepartemen(departemen);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui");
            resetForm();
            loadUsers();
            showPanelView(); 
            btnTambah.setText("Tambah");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

   private void deleteData() {
        int selectedRow = tabelDepartemen.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda ingin menghapus data ini ?",
                "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // Now ID is in column 1 (column 0 is sequence number)
                String idStr = tabelDepartemen.getValueAt(selectedRow, 1).toString();
                int id = Integer.parseInt(idStr);

                DepartemenController departemenController = new DepartemenController();
                boolean success = departemenController.deleteDepartemen(id);

                if (success) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                    loadUsers(); 
                    resetForm(); 
                    showPanelView();
                    btnTambah.setText("Tambah");
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    

}
