/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;


import controllers.AbsensiController;



import java.util.List;

import javax.swing.JDialog;


import javax.swing.table.DefaultTableModel;
import models.Absensi;




/**
 *
 * @author darwisy
 */
public class ReportAbsensi extends javax.swing.JPanel {

    /**
     * Creates new form User
     */
    public ReportAbsensi() {
        initComponents();
        setTableAbsensi();
        loadAbsensi();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAbsensi = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        printReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setText("Report > Absensi");

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setText("Laporan Absensi");

        tabelAbsensi.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tabelAbsensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelAbsensi.setGridColor(new java.awt.Color(204, 204, 204));
        tabelAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAbsensiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelAbsensi);

        txtSearch.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtSearch.setText("Search...");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        printReport.setBackground(new java.awt.Color(81, 108, 248));
        printReport.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        printReport.setForeground(new java.awt.Color(255, 255, 255));
        printReport.setText("Print ");
        printReport.setBorder(null);
        printReport.setHideActionText(true);
        printReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelViewLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelViewLayout.createSequentialGroup()
                        .addComponent(printReport, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printReport, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panelMain.add(panelView, "card9");

        add(panelMain, "card9");
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        searchData();
    }//GEN-LAST:event_txtSearchKeyTyped

    private void tabelAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAbsensiMouseClicked

    }//GEN-LAST:event_tabelAbsensiMouseClicked

    private void printReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReportActionPerformed
        JDialog dialog = new JDialog();
        dialog.setTitle("Report");
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE); 
        dialog.add(new ReportAbsensiDate()); // Your panel

        // Auto-size, center, and show
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        
        
           
            
    }//GEN-LAST:event_printReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelView;
    private javax.swing.JButton printReport;
    private javax.swing.JTable tabelAbsensi;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    
    
    
    private void loadAbsensi() {
        
        AbsensiController absensiController = new AbsensiController();
        List<Absensi> absensis = absensiController.getAllAbsensi();

        DefaultTableModel model = (DefaultTableModel)tabelAbsensi.getModel(); 
        model.setRowCount(0);

        if (absensis != null) {
            int number = 1;
            for (Absensi absensi : absensis) {
                model.addRow(new Object[]{
                    number++,
                    absensi.getKdAbsensi(),
                    absensi.getKaryawan(),
                    absensi.getTanggal(),
                    absensi.getStatus(),
                    absensi.getKeterangan(),
                });
            }
        }
    }

    private void setTableAbsensi() {
        DefaultTableModel model = new DefaultTableModel() {
        @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make all cells non-editable
            }
        };
        model.addColumn("No");
        model.addColumn("Kode Absensi");
        model.addColumn("Nama Karyawan");
        model.addColumn("Tanggal");
        model.addColumn("Status");
        model.addColumn("Keterangan");
        
        tabelAbsensi.setModel(model);
        tabelAbsensi.getColumnModel().getColumn(0).setPreferredWidth(10);   
        tabelAbsensi.getColumnModel().getColumn(1).setPreferredWidth(80);   
        tabelAbsensi.getColumnModel().getColumn(2).setPreferredWidth(150);  
        tabelAbsensi.getColumnModel().getColumn(3).setPreferredWidth(120);  
        tabelAbsensi.getColumnModel().getColumn(4).setPreferredWidth(150);  
        tabelAbsensi.getColumnModel().getColumn(5).setPreferredWidth(100);  

    }

    
    
   private void searchData() {
        String keyword = txtSearch.getText();
        AbsensiController absensiController = new AbsensiController();
        List<Absensi> absensis = absensiController.searchAbsensis(keyword);

        DefaultTableModel model = (DefaultTableModel) tabelAbsensi.getModel();
        model.setRowCount(0);

        int number = 1;
        for (Absensi absensi : absensis) {
            model.addRow(new Object[]{
                number++,
                absensi.getKdAbsensi(), 
                absensi.getKaryawan(),
                absensi.getTanggal(),
                absensi.getStatus(),
                absensi.getKeterangan(),
            });
        }
    }



    

    

}
