/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;




import controllers.JabatanController;
import controllers.KaryawanController;
import controllers.SlipGajiController;
import controllers.DetailGajiController;
import java.awt.Component;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.DetailGaji;
import models.Jabatan;
import models.Karyawan;
import models.SlipGaji;

/**
 *
 * @author darwisy
 */
public class ReportPenggajian extends javax.swing.JPanel {

    /**
     * Creates new form User
     */
    public ReportPenggajian() {
        initComponents();
        setTableGaji();
       
        loadGaji();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSlip = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Report > Penggajian");
        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jLabel2.setText("Penggajian");
        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N

        txtSearch.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtSearch.setText("Search...");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        btnPrint.setText("Print");
        btnPrint.setBackground(new java.awt.Color(81, 108, 248));
        btnPrint.setBorder(null);
        btnPrint.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        tableSlip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSlip.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tableSlip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSlipMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSlip);

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(535, 535, 535)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panelMain.add(panelView, "card9");

        add(panelMain, "card9");
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        JDialog dialog = new JDialog();
        dialog.setTitle("Report");
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE); 
        dialog.add(new ReportPenggajianDate()); // Your panel
        // Auto-size, center, and show
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);


    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        searchData();
    }//GEN-LAST:event_txtSearchKeyTyped

    private void tableSlipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSlipMouseClicked
        if(btnPrint.getText().equals("Tambah")){
            btnPrint.setText("Ubah");
        }
       
    }//GEN-LAST:event_tableSlipMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelView;
    private javax.swing.JTable tableSlip;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    
    private void showPanelView(){
        panelMain.removeAll();
        panelMain.add(panelView);

        
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    private void loadGaji() {

        SlipGajiController slipGajiController = new SlipGajiController();
        List<SlipGaji> slipgajis = slipGajiController.getAllSlipGaji();

        DefaultTableModel model = (DefaultTableModel)tableSlip.getModel(); 
        model.setRowCount(0);

        if (slipgajis != null) {
            for (SlipGaji slipgaji : slipgajis) {
                model.addRow(new Object[]{
                    slipgaji.getKdSlip(),
                    slipgaji.getKaryawan(),
                    slipgaji.getPeriode(),
                    slipgaji.getGajiPokok(),
                    slipgaji.getTotalTambahan(),
                    slipgaji.getTotalPengurangan(),
                    slipgaji.getGajiBersih()
                });
            }
        }
        
        

        
    }

    private void setTableGaji() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Slip");
        model.addColumn("Nama Karyawan");
        model.addColumn("Periode");
        model.addColumn("Gaji Pokok");
        model.addColumn("Penambahan");
        model.addColumn("Pengurangan");
        model.addColumn("Total");

        tableSlip.setModel(model);

        // Optional: Set preferred column widths if needed
        tableSlip.getColumnModel().getColumn(0).setPreferredWidth(80); // Kode Slip
        tableSlip.getColumnModel().getColumn(1).setPreferredWidth(150); // Nama Karyawan
        tableSlip.getColumnModel().getColumn(2).setPreferredWidth(100);  // Periode
        tableSlip.getColumnModel().getColumn(3).setPreferredWidth(100); // Gaji Pokok
        tableSlip.getColumnModel().getColumn(4).setPreferredWidth(100); // Penambahan
        tableSlip.getColumnModel().getColumn(5).setPreferredWidth(100); // Pengurangan
        tableSlip.getColumnModel().getColumn(6).setPreferredWidth(120); // Total
    }

   
    private void searchData() {
        String keyword = txtSearch.getText();
        SlipGajiController slipGajiController = new SlipGajiController();
        List<SlipGaji> slipgajis = slipGajiController.searchSlipGajis(keyword);

        DefaultTableModel model = (DefaultTableModel) tableSlip.getModel();
        model.setRowCount(0);

        for (SlipGaji slipgaji : slipgajis) {
            model.addRow(new Object[]{
                slipgaji.getKdSlip(),
                
                    slipgaji.getKaryawan(),
                    slipgaji.getPeriode(),
                    slipgaji.getGajiPokok(),
                    slipgaji.getTotalTambahan(),
                    slipgaji.getTotalPengurangan(),
                    slipgaji.getGajiBersih()
            });
        }
    }

}

