/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;


import controllers.RekrutmenController;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Rekrutmen;

/**
 *
 * @author darwisy
 */
public class TrxRekrutmen extends javax.swing.JPanel {

    /**
     * Creates new form User
     */
    public TrxRekrutmen() {
        initComponents();
        setTableRekrutmen();
        loadRekrutmen();
        loadComboStatus();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelRekrutmen = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        panelAdd = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnTambahBatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tambahNama = new javax.swing.JTextField();
        tambahKD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tambahEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tambahTelepon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tambahPosisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tambahStatus = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnTambahReset = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setText("Transaksi> Rekrutmen");

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel11.setText("Data Rekrutmen");

        tabelRekrutmen.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tabelRekrutmen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelRekrutmen.setGridColor(new java.awt.Color(204, 204, 204));
        tabelRekrutmen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRekrutmenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelRekrutmen);

        txtSearch.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtSearch.setText("Search...");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(81, 108, 248));
        btnTambah.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.setBorder(null);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(248, 173, 80));
        btnBatal.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.setBorder(null);
        btnBatal.setPreferredSize(new java.awt.Dimension(62, 22));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(248, 80, 108));
        btnDelete.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Hapus");
        btnDelete.setBorder(null);
        btnDelete.setPreferredSize(new java.awt.Dimension(62, 22));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewLayout.createSequentialGroup()
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelViewLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panelMain.add(panelView, "card9");

        panelAdd.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Transaksi > Rekrutmen");

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel4.setText("Tambah Data Rekrutmen");

        btnSimpan.setBackground(new java.awt.Color(81, 108, 248));
        btnSimpan.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTambahBatal.setBackground(new java.awt.Color(248, 173, 80));
        btnTambahBatal.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnTambahBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahBatal.setText("Batal");
        btnTambahBatal.setBorder(null);
        btnTambahBatal.setMaximumSize(new java.awt.Dimension(90, 28));
        btnTambahBatal.setMinimumSize(new java.awt.Dimension(90, 28));
        btnTambahBatal.setPreferredSize(new java.awt.Dimension(90, 28));
        btnTambahBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBatalActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Kode Rekrutmen");

        tambahNama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        tambahKD.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("Email");

        tambahEmail.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("No Telepon");

        tambahTelepon.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Posisi ");

        tambahPosisi.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setText("Status");

        tambahStatus.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tambahStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setText("Nama Pelamar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahNama)
                    .addComponent(tambahEmail)
                    .addComponent(tambahTelepon)
                    .addComponent(tambahPosisi)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambahStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tambahKD))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahKD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahPosisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );

        btnTambahReset.setBackground(new java.awt.Color(51, 51, 51));
        btnTambahReset.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnTambahReset.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahReset.setText("Reset");
        btnTambahReset.setBorder(null);
        btnTambahReset.setMaximumSize(new java.awt.Dimension(90, 28));
        btnTambahReset.setMinimumSize(new java.awt.Dimension(90, 28));
        btnTambahReset.setPreferredSize(new java.awt.Dimension(90, 28));
        btnTambahReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 442, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddLayout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnTambahReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnTambahBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMain.add(panelAdd, "card9");

        add(panelMain, "card9");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String currentText = btnSimpan.getText();

        switch (currentText) {
            case "Tambah":
                btnSimpan.setText("Simpan");
                break;
            case "Simpan":
                insertData();
                break;

            case "Perbarui":
                updateData();
                break;
        }
        
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBatalActionPerformed
        showPanelView();
        loadRekrutmen();
        resetForm();
        if(btnTambah.getText().equals("Ubah")){
            btnTambah.setText("Tambah");
        }
    }//GEN-LAST:event_btnTambahBatalActionPerformed

    private void btnTambahResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahResetActionPerformed
        resetForm();
    }//GEN-LAST:event_btnTambahResetActionPerformed

    private void tabelRekrutmenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRekrutmenMouseClicked
        if(btnTambah.getText().equals("Tambah")){
            btnTambah.setText("Ubah");
        }
        btnBatal.setVisible(true);
        btnDelete.setVisible(true);
    }//GEN-LAST:event_tabelRekrutmenMouseClicked

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        searchData();
    }//GEN-LAST:event_txtSearchKeyTyped

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        panelMain.removeAll();
        panelMain.add(panelAdd);
        panelMain.repaint();
        panelMain.revalidate();
        

        if (btnTambah.getText().equals("Ubah")) {
            dataTable();
            btnSimpan.setText("Perbarui");
            tambahKD.setEditable(false);
        } else {
            resetForm();
            btnSimpan.setText("Simpan");
            tambahKD.setText(generateKodeRekrutmen());
            tambahKD.setEditable(false);

        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        showPanelView();
        loadRekrutmen();
        resetForm();
        if(btnTambah.getText().equals("Ubah")){
            btnTambah.setText("Tambah");
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteData();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahBatal;
    private javax.swing.JButton btnTambahReset;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelView;
    private javax.swing.JTable tabelRekrutmen;
    private javax.swing.JTextField tambahEmail;
    private javax.swing.JTextField tambahKD;
    private javax.swing.JTextField tambahNama;
    private javax.swing.JTextField tambahPosisi;
    private javax.swing.JComboBox<String> tambahStatus;
    private javax.swing.JTextField tambahTelepon;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    
    private void showPanelView(){
        panelMain.removeAll();
        panelMain.add(panelView);
        btnBatal.setVisible(false);
        btnDelete.setVisible(false);
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    private void loadRekrutmen() {
           
        btnBatal.setVisible(false);
        btnDelete.setVisible(false);
        RekrutmenController rekrutmenController = new RekrutmenController();
        List<Rekrutmen> rekrutmens = rekrutmenController.getAllRekrutmen();
        
        DefaultTableModel model = (DefaultTableModel)tabelRekrutmen.getModel(); 
        model.setRowCount(0);
        
        if (rekrutmens != null) {
            for (Rekrutmen rekrutmen : rekrutmens) {
                model.addRow(new Object[]{
                    rekrutmen.getKdRekrutmen(),
                    rekrutmen.getNamaPelamar(),
                    rekrutmen.getEmail(),
                    rekrutmen.getTelepon(),
                    rekrutmen.getPosisi(),
                    rekrutmen.getStatus(),
                    
                    
                });
            }
        }

        
    }

    private void setTableRekrutmen() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Rekrutmen");
        model.addColumn("Nama Pelamar");
        model.addColumn("Email");
        model.addColumn("No. Telepon");
        model.addColumn("Posisi");
        model.addColumn("Status");
        tabelRekrutmen.setModel(model);
        
    }

    private void resetForm() {
        tambahNama.setText("");
        
        tambahEmail.setText("");
        tambahTelepon.setText("");
        tambahPosisi.setText("");
        // Reset combo boxes
        
        tambahStatus.setSelectedIndex(0);
        

        // Reset focus
        tambahNama.requestFocusInWindow();
    }
    
    private void searchData() {
        String keyword = txtSearch.getText();
        RekrutmenController rekrutmenController = new RekrutmenController();
        List<Rekrutmen> rekrutmens = rekrutmenController.searchRekrutmens(keyword);

        DefaultTableModel model = (DefaultTableModel) tabelRekrutmen.getModel();
        model.setRowCount(0);

        for (Rekrutmen rekrutmen : rekrutmens) {
            model.addRow(new Object[]{
                rekrutmen.getKdRekrutmen(), 
                rekrutmen.getNamaPelamar(),
                rekrutmen.getEmail(),
                rekrutmen.getTelepon(),
                rekrutmen.getPosisi(),
                rekrutmen.getStatus(),
            });
        }
    }

    private void dataTable(){
        panelView.setVisible(false);
        panelAdd.setVisible(true);
        
        int row = tabelRekrutmen.getSelectedRow();
        jLabel4.setText("Ubah Data Rekrutmen");
        
        tambahNama.setText(tabelRekrutmen.getValueAt(row, 1).toString());
        tambahEmail.setText(tabelRekrutmen.getValueAt(row, 2).toString());
        tambahTelepon.setText(tabelRekrutmen.getValueAt(row, 3).toString());
        tambahPosisi.setText(tabelRekrutmen.getValueAt(row, 4).toString());
        
        setComboFromTable(tambahStatus, tabelRekrutmen.getValueAt(row, 5).toString());
        
        String id = tabelRekrutmen.getValueAt(row, 0).toString(); 
        tambahKD.setText(id);
        
        
    }
    
    private void insertData() {
        String kd = tambahKD.getText();
        String nama = tambahNama.getText();
        String email = tambahEmail.getText();
        String teleponStr = tambahTelepon.getText();
        String posisi = tambahPosisi.getText();
        
        String status = (String) tambahStatus.getSelectedItem();
        // Validate phone number
        if (teleponStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nomor telepon harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convert String to long
        long telepon;
        try {
            telepon = Long.parseLong(teleponStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nomor telepon harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Rekrutmen rekrutmen = new Rekrutmen();
        rekrutmen.setKdRekrutmen(kd);
        rekrutmen.setNamaPelamar(nama);
        rekrutmen.setEmail(email);
        rekrutmen.setTelepon(telepon);
        rekrutmen.setPosisi(posisi);
        rekrutmen.setStatus(status);
        
        
        // Simpan lewat controller
        RekrutmenController rekrutmenController = new RekrutmenController();
        boolean success = rekrutmenController.insertRekrutmen(rekrutmen);

        if (success) {
            JOptionPane.showMessageDialog(this, "Rekrutmen berhasil ditambahkan!");
            loadRekrutmen(); 
            resetForm(); 
            showPanelView(); 
            btnTambah.setText("Tambah");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan Rekrutmen.");
        }
    }

    private void updateData() {
        
        String kdStr = tambahKD.getText();
        String nama = tambahNama.getText();
        String email = tambahEmail.getText();
        String teleponStr = tambahTelepon.getText();
        String posisi = tambahPosisi.getText();
        
        String status = (String) tambahStatus.getSelectedItem();
        // Validate phone number
        if (teleponStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nomor telepon harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convert String to long
        long telepon;
        try {
            telepon = Long.parseLong(teleponStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nomor telepon harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Rekrutmen rekrutmen = new Rekrutmen();
        rekrutmen.setKdRekrutmen(kdStr); 
        rekrutmen.setNamaPelamar(nama);
        rekrutmen.setEmail(email);
        rekrutmen.setTelepon(telepon);
        rekrutmen.setPosisi(posisi);
        rekrutmen.setStatus(status);
        
        
        // Simpan lewat controller
        RekrutmenController rekrutmenController = new RekrutmenController();
        boolean success = rekrutmenController.updateRekrutmen(rekrutmen);

        if (success) {
            JOptionPane.showMessageDialog(this, "Rekrutmen berhasil diubah!");
            loadRekrutmen(); 
            resetForm(); 
            showPanelView(); 
            btnTambah.setText("Tambah");
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengubah Rekrutmen.");
        }
    }

    private void deleteData() {
        int selectedRow = tabelRekrutmen.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda ingin menghapus data ini ?",
                "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                
                String kdStr = tabelRekrutmen.getValueAt(selectedRow, 0).toString();
                

                RekrutmenController rekrutmenController = new RekrutmenController();
                boolean success = rekrutmenController.deleteRekrutmen(kdStr);

                if (success) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                    loadRekrutmen(); 
                    resetForm(); 
                    showPanelView();
                    btnTambah.setText("Tambah");

                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    
private void loadComboStatus() {
        tambahStatus.removeAllItems();
        tambahStatus.addItem("Wawancara");
        tambahStatus.addItem("Diterima");
        tambahStatus.addItem("Ditolak");
 }

 private void setComboFromTable(JComboBox<?> combo, String value) {
    for (int i = 0; i < combo.getItemCount(); i++) {
        Object item = combo.getItemAt(i);
        String displayValue = item.toString(); // Works for both String and objects with toString()
        if (displayValue.equalsIgnoreCase(value)) {
            combo.setSelectedIndex(i);
            return;
        }
    }
    // If not found, select first item or none
    if (combo.getItemCount() > 0) {
        combo.setSelectedIndex(0);
    }
}

    private String generateKodeRekrutmen() {
        RekrutmenController controller = new RekrutmenController();
        String lastKode = controller.getLastKodeRekrutmen();

        if (lastKode == null || lastKode.isEmpty()) {
            return "RKT-001"; // If no employees exist yet
        }

        try {
            // Extract the numeric part
            String numericPart = lastKode.split("-")[1];
            int number = Integer.parseInt(numericPart);

            // Increment and format with leading zeros
            return String.format("RKT-%03d", number + 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error generating employee code: " + e.getMessage());
            return "RKT-001"; // Fallback
        }

    }

}
